version: '2.3'
services:
  dns:
    image: dns:latest
    command:
      - --config
      - /app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    networks:
      dns:
        ipv4_address: 10.5.0.5

networks:
  dns:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1